### ISSUE TITLE
ML Method 1: Use "optrdd" package on RDD

### ISSUE THREAD

**Issue by christineykim** [christineykim/ECON293_Research-Project#1]

**Comment by ellamao1120** [comment]
- [x] Fixed effects (confoundedness)
- [x] Sensible levels of B
- [ ] optimizer == quadprog 
- [x] Should we use elastic net?
- [x] Should we use num.bucket?

References:
R package (https://github.com/swager/optrdd)
Paper (https://arxiv.org/pdf/1705.01677.pdf)

**Comment by ellamao1120** [comment]
Used lm_forest package in the end.
